In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))       #type(): This built-in Python function tells us the type of the object passed to it.

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)


[1 2 3 4 5]


In [3]:
a=np.random.random((2,2))

In [4]:
a


array([[0.48967789, 0.99103179],
       [0.3408546 , 0.00628078]])

In [5]:
a1D = np.array([1, 2, 3, 4])
a2D = np.array([[1, 2], [3, 4]])
a3D = np.array([[[1, 2], [3, 4]],
                    [[5, 6], [7, 8]]])

print(a1D.ndim)
print(a2D.ndim)
print(a3D.ndim)


1
2
3


In [6]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [7]:
import numpy as np
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )
print("Shape of array: ", arr.shape)

print("Size of array: ", arr.size)
  

Shape of array:  (2, 3)
Size of array:  6


In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4])  

print(arr[1])

arr2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])     #Access 2-D Arrays

print('5th element on 2nd dim: ', arr2[1, 4])

arr3= np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])   #Access 3-D Arrays

print(arr3[0, 1, 2])


2
5th element on 2nd dim:  10
6


In [9]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [10]:
arr[-1]

array([ 6,  7,  8,  9, 10])

In [11]:
arr[-1][-1]

10

In [12]:
#Slice elements from the beginning to index 4 (not included):

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])


[1 2 3 4]


In [13]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])


[5 6]


In [14]:
#Return every other element from index 1 to index 5:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])



[2 4]


In [15]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [16]:
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b=a[:2, 1:3]#passed by reference
b

array([[2, 3],
       [6, 7]])

In [17]:
# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"


2
77


In [18]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])


In [19]:
# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


In [20]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [21]:
import numpy as np

x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)        

x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             

x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)                         


int64
float64
int64


In [22]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
print(np.sqrt(x))


[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


**Note that here * is elementwise multiplication, not matrix multiplication. We instead use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. Example:**



In [26]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])
c=np.array([[9],[10]])

# Matrix / vector product; both produce the rank 1 array
print(x.dot(v))
print(x.dot(c))
print(v.dot(x))
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
print(x.dot(y))
print(np.dot(x, y))



[29 67]
[[29]
 [67]]
[39 58]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [27]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))          # Compute sum of all elements
print(np.sum(x, axis=0))  # Compute sum of each column
print(np.sum(x, axis=1))  # Compute sum of each row

10
[4 6]
[3 7]


In [28]:
x = np.array([[1,2], [3,4]])
print(x)    
print(x.T)  

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)    
print(v.T)  


[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


In [29]:
import numpy as np
    
# Original array
a = np.array([[1, 2], [3, 4]])

print("\nMean:",np.mean(a))   #The default is to compute the mean of the flattened array.

print("\nMean:" ,np.mean(a, axis=0))  # Mean taken over the specified axis 
  
print("\nstd:" ,np.std(a))   #The default is to compute the mean of the flattened array.

print("\nstd:" ,np.std(a, axis=0))   #standard deviation computed over the specified axis.

print("\nvariance:" ,np.var(a))  # variance is computed for the flattened array by default

print("\nvariance:" ,np.var(a, axis=0))  #variance computed over the specified axis.



Mean: 2.5

Mean: [2. 3.]

std: 1.118033988749895

std: [1. 1.]

variance: 1.25

variance: [1. 1.]
